export const TASK = {
  id: "unit-3-listen-meaning",
  name: "听音辨义",
  grade: "高二",
  duration: "约 6 分钟",
  replayThreshold: 2,
};

export const WORDS = [
  {
    id: "solution",
    word: "solution",
    phonetic: "/səˈluːʃn/",
    meaning: "解决办法；答案",
    options: ["解决办法；答案", "意外事故", "公共交通", "个人习惯"],
    tip: "solution 常指解决问题的方法，也可以指答案。",
  },
  {
    id: "achieve",
    word: "achieve",
    phonetic: "/əˈtʃiːv/",
    meaning: "达到；实现",
    options: ["重复；复述", "达到；实现", "邀请；请求", "移动；搬运"],
    tip: "achieve a goal 表示实现一个目标。",
  },
  {
    id: "affect",
    word: "affect",
    phonetic: "/əˈfekt/",
    meaning: "影响；作用于",
    options: ["预测；预报", "接受；同意", "影响；作用于", "保护；保卫"],
    tip: "affect 常作动词，表示对人或事物产生影响。",
  },
  {
    id: "increase",
    word: "increase",
    phonetic: "/ɪnˈkriːs/",
    meaning: "增加；增长",
    options: ["减少；降低", "增加；增长", "解释；说明", "练习；训练"],
    tip: "increase 与 decrease 意思相反。",
  },
  {
    id: "discover",
    word: "discover",
    phonetic: "/dɪˈskʌvə(r)/",
    meaning: "发现；发觉",
    options: ["决定；选择", "发现；发觉", "失去；错过", "记住；回想"],
    tip: "discover 强调发现此前不知道的事物。",
  },
  {
    id: "natural",
    word: "natural",
    phonetic: "/ˈnætʃrəl/",
    meaning: "自然的；天然的",
    options: ["自然的；天然的", "迅速的；立刻的", "危险的；有害的", "国外的；海外的"],
    tip: "natural 来自 nature，表示与自然有关。",
  },
  {
    id: "sudden",
    word: "sudden",
    phonetic: "/ˈsʌdn/",
    meaning: "突然的；忽然的",
    options: ["耐心的；平静的", "突然的；忽然的", "传统的；常见的", "明显的；清楚的"],
    tip: "a sudden change 表示突然的变化。",
  },
  {
    id: "possible",
    word: "possible",
    phonetic: "/ˈpɒsəbl/",
    meaning: "可能的；可行的",
    options: ["重要的；主要的", "困难的；复杂的", "可能的；可行的", "完整的；全部的"],
    tip: "possible 表示某件事有可能发生或做到。",
  },
  {
    id: "invite",
    word: "invite",
    phonetic: "/ɪnˈvaɪt/",
    meaning: "邀请；招待",
    options: ["邀请；招待", "避免；防止", "借出；租出", "检查；核对"],
    tip: "invite someone to 表示邀请某人参加活动。",
  },
  {
    id: "limit",
    word: "limit",
    phonetic: "/ˈlɪmɪt/",
    meaning: "限制；限定",
    options: ["允许；准许", "限制；限定", "讨论；交流", "完成；结束"],
    tip: "limit 可以表示规定范围或数量。",
  },
];
