export const READING_WRITING_TASK = {
  id: "unit-3-reading-writing",
  name: "阅读写作",
  grade: "高二",
  duration: "约 12 分钟",
};

export const ROLE_LABELS = {
  difficulty: "表示困难",
  quantity: "数量很多",
  accuracy: "准确使用",
  result: "引出结果",
  contrast: "形成对比",
  trend: "描述趋势",
  proportion: "说明占比",
  concession: "先让步",
  importance: "强调作用",
};

export const CHUNK_BANK = [
  {
    word: "number",
    chunk: "a large number of",
    zh: "大量的",
    role: "quantity",
    alternatives: ["many", "a considerable number of"],
    tip: "后接可数名词复数，用来概括人或事物数量。",
  },
  {
    word: "struggle",
    chunk: "struggle to do",
    zh: "难以做某事",
    role: "difficulty",
    alternatives: ["find it difficult to do", "have difficulty doing"],
    tip: "说明某个群体在能力或表现上的困难。",
  },
  {
    word: "accurate",
    chunk: "use sth accurately",
    zh: "准确使用某物",
    role: "accuracy",
    alternatives: ["apply sth correctly", "use sth with precision"],
    tip: "用 accurately 修饰 use、describe、measure 等动作。",
  },
  {
    word: "lead",
    chunk: "lead to",
    zh: "导致",
    role: "result",
    alternatives: ["result in", "give rise to"],
    tip: "连接原因和结果，to 不能省略。",
  },
  {
    word: "increase",
    chunk: "a sharp increase in",
    zh: "急剧增长",
    role: "trend",
    alternatives: ["a dramatic rise in", "a significant growth in"],
    tip: "描述数据快速上升，后面常接名词。",
  },
  {
    word: "account",
    chunk: "account for",
    zh: "占比；解释",
    role: "proportion",
    alternatives: ["make up", "represent"],
    tip: "说明某项数据占多少比例。",
  },
  {
    word: "result",
    chunk: "as a result",
    zh: "因此",
    role: "result",
    alternatives: ["therefore", "consequently"],
    tip: "引出前文原因带来的结果。",
  },
  {
    word: "despite",
    chunk: "despite the fact that",
    zh: "尽管事实是",
    role: "concession",
    alternatives: ["although", "even though"],
    tip: "先承认一个事实，再转向更重要的观点。",
  },
  {
    word: "contrast",
    chunk: "in contrast",
    zh: "相比之下",
    role: "contrast",
    alternatives: ["by contrast", "whereas"],
    tip: "连接两个相反或明显不同的情况。",
  },
  {
    word: "play",
    chunk: "play a crucial role in",
    zh: "发挥关键作用",
    role: "importance",
    alternatives: ["be essential to", "be central to"],
    tip: "强调某因素的重要性，role 后通常接 in。",
  },
];

export const READING_WRITING_SETS = [
  {
    id: "vocabulary-accuracy",
    title: "词汇量与准确使用",
    focus: "把认识的词放进句子和词块里使用",
    sourceCards: [
      {
        word: "number",
        partOfSpeech: "n.",
        sentence: "Many students know a large number of English words.",
        translation: "许多学生认识大量英语单词。",
        nonTargetTranslation: "许多学生认识 ____ 英语单词。",
        analysis: "a large number of 是数量词块，后面接可数名词复数 English words。",
        collocation: "a large number of + plural noun",
        answer: "大量的",
        choices: ["总数", "大量的", "排名", "编号"],
      },
      {
        word: "struggle",
        partOfSpeech: "v.",
        sentence: "However, they still struggle to use them accurately in writing.",
        translation: "然而，他们在写作中仍然难以准确使用这些词。",
        nonTargetTranslation: "然而，他们在写作中仍然 ____ 准确使用这些词。",
        analysis: "struggle to use 不是身体上的挣扎，而是在语境中表示“难以做到”。",
        collocation: "struggle to + verb",
        answer: "难以做某事",
        choices: ["长期奋斗", "挣扎着移动", "难以做某事", "努力争取"],
      },
      {
        word: "accurate",
        partOfSpeech: "adv.",
        sentence: "They still struggle to use them accurately in writing.",
        translation: "他们在写作中仍然难以准确使用这些词。",
        nonTargetTranslation: "他们在写作中仍然难以 ____ 使用这些词。",
        analysis: "accurately 修饰 use，重点是“用得是否准确”。",
        collocation: "use something accurately",
        answer: "准确地",
        choices: ["完整地", "恰当地", "准确地", "熟练地"],
      },
      {
        word: "lead",
        partOfSpeech: "v.",
        sentence: "This habit can lead to unnatural sentences and repeated grammar mistakes.",
        translation: "这个习惯会导致句子不自然和反复出现语法错误。",
        nonTargetTranslation: "这个习惯会 ____ 句子不自然和反复出现语法错误。",
        analysis: "lead to 在这里连接原因和结果，表示“导致”。",
        collocation: "lead to + result",
        answer: "导致",
        choices: ["引导", "负责", "导致", "处于领先"],
      },
    ],
    passageTitle: "阅读短文：词汇量和写作准确度",
    passage:
      "Many students know a large number of English words. However, they still struggle to use them accurately in writing. One reason is that they often learn words as isolated items rather than as chunks. This habit can lead to unnatural sentences and repeated grammar mistakes. In contrast, students who notice phrases in reading are more likely to reuse them in essays.",
    sentenceTranslations: [
      "许多学生认识大量英语单词。",
      "然而，他们在写作中仍然难以准确使用这些词。",
      "一个原因是他们经常把单词作为孤立项目来学，而不是作为词块来学。",
      "这个习惯会导致句子不自然和反复出现语法错误。",
      "相比之下，在阅读中注意短语的学生更可能在作文中复用它们。",
    ],
    retrieval: [
      {
        sourceWord: "number",
        task: "学生词汇量不少",
        sentenceIndex: 0,
        meaningQuestion: "这句话主要说明什么？",
        meaningOptions: ["学生认识很多英语单词", "学生经常写很多英语句子", "学生学习很多语法规则"],
        meaningAnswer: "学生认识很多英语单词",
        expected: "a large number of",
        targetChunk: "a large number of",
        targetHighlight: "a large number of English words",
      },
      {
        sourceWord: "struggle",
        task: "学生知道词，但写作中用不好",
        sentenceIndex: 1,
        meaningQuestion: "这句话里的困难具体是什么？",
        meaningOptions: ["学生难以准确使用这些词", "学生完全不认识这些词", "学生不愿意写作文"],
        meaningAnswer: "学生难以准确使用这些词",
        expected: "struggle to use",
        targetChunk: "struggle to do",
        targetHighlight: "struggle to use them accurately",
      },
      {
        sourceWord: "lead",
        task: "孤立背词会带来后果",
        sentenceIndex: 3,
        meaningQuestion: "这个习惯造成了什么后果？",
        meaningOptions: ["句子不自然，并反复出现语法错误", "学生阅读速度明显下降", "学生完全无法理解文章"],
        meaningAnswer: "句子不自然，并反复出现语法错误",
        expected: "lead to",
        targetChunk: "lead to",
        targetHighlight: "lead to unnatural sentences and repeated grammar mistakes",
      },
    ],
    judge: [
      {
        chunk: "struggle to use",
        targetChunk: "struggle to do",
        sentence: "They still struggle to use them accurately in writing.",
        meaningAnswer: "难以做某事",
        meaningOptions: ["难以做某事", "长期奋斗", "快速完成", "努力争取胜利"],
        meaningAccepts: ["很难", "困难", "不容易", "做不到"],
        nonTargetTranslation: "他们仍然在写作中准确使用这些词。",
        roleOptions: ["表示学习困难", "表示数量很多", "表示结果", "形成对比"],
        roleExplanation: "在例句中表示学生写作时遇到的困难。",
        roleAnswer: "difficulty",
      },
      {
        chunk: "lead to",
        targetChunk: "lead to",
        sentence: "This habit can lead to unnatural sentences and repeated grammar mistakes.",
        meaningAnswer: "导致",
        meaningOptions: ["导致", "引导", "处于领先", "负责"],
        meaningAccepts: ["引起", "造成", "带来", "产生"],
        nonTargetTranslation: "这个习惯和句子不自然、反复语法错误之间有关系。",
        roleOptions: ["引出结果", "表示让步", "说明数量", "补充例子"],
        roleExplanation: "在例句中连接原因和后果，引出不自然句子和语法错误这个结果。",
        roleAnswer: "result",
      },
    ],
    application: {
      context: "班里在讨论学习方法：有同学每天背很多单词，但写英文句子时还是常常用错。",
      prompt: "请用英文写 1 个简单观点：你认为只背很多单词够不够。",
      minChunks: 1,
      minWords: 8,
      sample: "A large number of words do not help if students struggle to use them accurately.",
    },
  },
  {
    id: "chart-trend",
    title: "图表趋势与原因表达",
    focus: "用词块描述趋势、占比和结果",
    sourceCards: [
      {
        word: "increase",
        partOfSpeech: "n.",
        sentence: "The data shows a sharp increase in the use of online courses.",
        translation: "数据显示，线上课程的使用出现了急剧增长。",
        nonTargetTranslation: "数据显示，线上课程的使用出现了 ____。",
        analysis: "a sharp increase in 用来描述数据明显上升。",
        collocation: "a sharp increase in + noun",
        answer: "增长",
        choices: ["增长", "提高", "增加量", "扩展"],
      },
      {
        word: "account",
        partOfSpeech: "v.",
        sentence: "Online courses accounted for only a small proportion of adult education.",
        translation: "线上课程只占成人教育的一小部分。",
        nonTargetTranslation: "线上课程 ____ 成人教育的一小部分。",
        analysis: "account for 在数据语境中常表示“占比”。",
        collocation: "account for + percentage/proportion",
        answer: "占比",
        choices: ["解释", "叙述", "占比", "账户"],
      },
      {
        word: "result",
        partOfSpeech: "phrase",
        sentence: "As a result, more adults were able to study while working full-time.",
        translation: "因此，更多成年人能够一边全职工作一边学习。",
        nonTargetTranslation: "____，更多成年人能够一边全职工作一边学习。",
        analysis: "as a result 放在句首，引出前面变化带来的结果。",
        collocation: "As a result, + result sentence",
        answer: "结果",
        choices: ["结论", "原因", "影响", "结果"],
      },
    ],
    passageTitle: "阅读短文：线上课程趋势",
    passage:
      "The data shows a sharp increase in the use of online courses between 2015 and 2025. In 2015, online courses accounted for only a small proportion of adult education. This change was partly caused by flexible schedules and lower costs. As a result, more adults were able to study while working full-time.",
    sentenceTranslations: [
      "数据显示，2015 到 2025 年线上课程的使用急剧增长。",
      "2015 年，线上课程只占成人教育的一小部分。",
      "这种变化部分是由灵活的时间安排和较低成本造成的。",
      "因此，更多成年人能够一边全职工作一边学习。",
    ],
    retrieval: [
      {
        sourceWord: "increase",
        task: "线上课程使用量明显上升",
        sentenceIndex: 0,
        meaningQuestion: "这句话描述的是哪类数据变化？",
        meaningOptions: ["线上课程使用量急剧增长", "线上课程价格大幅下降", "成人教育人数减少"],
        meaningAnswer: "线上课程使用量急剧增长",
        expected: "a sharp increase in",
        targetChunk: "a sharp increase in",
        targetHighlight: "a sharp increase in the use of online courses",
      },
      {
        sourceWord: "account",
        task: "线上课程在成人教育中占比很小",
        sentenceIndex: 1,
        meaningQuestion: "这句话说明线上课程在 2015 年的占比怎样？",
        meaningOptions: ["只占成人教育的一小部分", "占成人教育的大部分", "完全没有出现在成人教育中"],
        meaningAnswer: "只占成人教育的一小部分",
        expected: "accounted for",
        targetChunk: "account for",
        targetHighlight: "accounted for only a small proportion",
      },
      {
        sourceWord: "result",
        task: "变化带来的结果",
        sentenceIndex: 3,
        meaningQuestion: "这个结果具体是什么？",
        meaningOptions: ["更多成年人可以边全职工作边学习", "更多成年人停止学习", "更多学校取消线上课程"],
        meaningAnswer: "更多成年人可以边全职工作边学习",
        expected: "As a result",
        targetChunk: "as a result",
        targetHighlight: "As a result",
      },
    ],
    judge: [
      {
        chunk: "a sharp increase in",
        targetChunk: "a sharp increase in",
        sentence: "The data shows a sharp increase in the use of online courses.",
        meaningAnswer: "急剧增长",
        meaningOptions: ["急剧增长", "缓慢下降", "占一部分", "解释原因"],
        meaningAccepts: ["快速增长", "明显上升", "大幅增加", "迅速增加"],
        nonTargetTranslation: "数据显示，线上课程的使用出现了某种变化。",
        roleOptions: ["描述趋势", "说明占比", "引出结果", "形成对比"],
        roleExplanation: "在例句中描述线上课程使用量快速上升的趋势。",
        roleAnswer: "trend",
      },
      {
        chunk: "accounted for",
        targetChunk: "account for",
        sentence: "Online courses accounted for only a small proportion of adult education.",
        meaningAnswer: "占比",
        meaningOptions: ["占比", "解释账户", "导致结果", "形成对比"],
        meaningAccepts: ["占", "占多少", "比例", "构成"],
        nonTargetTranslation: "线上课程和成人教育的一小部分有关。",
        roleOptions: ["说明占比", "描述趋势", "引出结果", "表示困难"],
        roleExplanation: "在例句中说明线上课程在成人教育中的比例。",
        roleAnswer: "proportion",
      },
    ],
    application: {
      context: "一份学习报告显示：2015 年只有 12% 的成年人使用 online courses；到 2025 年，这个比例升到 48%。",
      prompt: "请用英文写 1 句，描述这个明显变化。",
      minChunks: 1,
      minWords: 8,
      sample: "There was a sharp increase in the use of online courses.",
    },
  },
  {
    id: "argument-concession",
    title: "让步与论证推进",
    focus: "先承认事实，再转向更有力观点",
    sourceCards: [
      {
        word: "despite",
        partOfSpeech: "prep. phrase",
        sentence: "Despite the fact that online tools are convenient, students still need guidance.",
        translation: "尽管线上工具很方便，学生仍然需要指导。",
        nonTargetTranslation: "____ 线上工具很方便，学生仍然需要指导。",
        analysis: "despite the fact that 用来先承认一个事实，再转向后面的重点。",
        collocation: "Despite the fact that + clause",
        answer: "尽管",
        choices: ["尽管", "因此", "相比之下", "尤其是"],
      },
      {
        word: "contrast",
        partOfSpeech: "phrase",
        sentence: "In contrast, guided practice helps students notice useful chunks.",
        translation: "相比之下，有引导的练习帮助学生注意有用词块。",
        nonTargetTranslation: "____，有引导的练习帮助学生注意有用词块。",
        analysis: "in contrast 用来把前后两种情况形成对比。",
        collocation: "In contrast, + contrasting idea",
        answer: "相比之下",
        choices: ["作为结果", "相比之下", "大量的", "导致"],
      },
      {
        word: "play",
        partOfSpeech: "v. phrase",
        sentence: "Teachers play a crucial role in helping students use new language accurately.",
        translation: "教师在帮助学生准确使用新语言方面发挥关键作用。",
        nonTargetTranslation: "教师 ____ 帮助学生准确使用新语言。",
        analysis: "play a crucial role in 用来强调某人或某事的重要作用。",
        collocation: "play a crucial role in + noun/doing",
        answer: "发挥作用",
        choices: ["扮演游戏", "发挥作用", "播放声音", "提出问题"],
      },
    ],
    passageTitle: "阅读短文：工具便利和教师引导",
    passage:
      "Despite the fact that online tools are convenient, students still need guidance when they learn new expressions. Many learners copy words without noticing how they work in sentences. In contrast, guided practice helps students notice useful chunks and reuse them later. Teachers play a crucial role in turning vocabulary knowledge into accurate writing.",
    sentenceTranslations: [
      "尽管线上工具很方便，学生学习新表达时仍然需要指导。",
      "许多学习者只是复制单词，却没有注意它们在句子中如何发挥作用。",
      "相比之下，有引导的练习帮助学生注意有用词块，并在之后复用它们。",
      "教师在把词汇知识转化为准确写作方面发挥关键作用。",
    ],
    retrieval: [
      {
        sourceWord: "despite",
        task: "先承认线上工具很方便",
        sentenceIndex: 0,
        meaningQuestion: "这句话先承认了什么事实？",
        meaningOptions: ["线上工具很方便", "学生完全不需要老师", "词块练习没有帮助"],
        meaningAnswer: "线上工具很方便",
        expected: "Despite the fact that",
        targetChunk: "despite the fact that",
        targetHighlight: "Despite the fact that online tools are convenient",
      },
      {
        sourceWord: "contrast",
        task: "复制单词和有引导练习形成对比",
        sentenceIndex: 2,
        meaningQuestion: "这句话强调有引导练习的什么作用？",
        meaningOptions: ["帮助学生注意词块并复用", "让学生只背单词", "减少所有写作任务"],
        meaningAnswer: "帮助学生注意词块并复用",
        expected: "In contrast",
        targetChunk: "in contrast",
        targetHighlight: "In contrast",
      },
      {
        sourceWord: "play",
        task: "教师作用重要",
        sentenceIndex: 3,
        meaningQuestion: "教师在这里有什么作用？",
        meaningOptions: ["把词汇知识转成准确写作", "取消学生练习", "只检查单词拼写"],
        meaningAnswer: "把词汇知识转成准确写作",
        expected: "play a crucial role in",
        targetChunk: "play a crucial role in",
        targetHighlight: "play a crucial role in turning vocabulary knowledge into accurate writing",
      },
    ],
    judge: [
      {
        chunk: "Despite the fact that",
        targetChunk: "despite the fact that",
        sentence: "Despite the fact that online tools are convenient, students still need guidance.",
        meaningAnswer: "尽管事实是",
        meaningOptions: ["尽管事实是", "因此", "相比之下", "导致"],
        meaningAccepts: ["虽然", "尽管", "即使", "让步"],
        nonTargetTranslation: "线上工具很方便，学生仍然需要指导。",
        roleOptions: ["表示让步", "引出结果", "说明占比", "表示数量很多"],
        roleExplanation: "在例句中先承认线上工具方便，再转向学生仍需要指导。",
        roleAnswer: "concession",
      },
      {
        chunk: "play a crucial role in",
        targetChunk: "play a crucial role in",
        sentence: "Teachers play a crucial role in helping students use new language accurately.",
        meaningAnswer: "发挥关键作用",
        meaningOptions: ["发挥关键作用", "播放重要角色", "形成对比", "说明占比"],
        meaningAccepts: ["很重要", "关键作用", "重要作用", "发挥作用"],
        nonTargetTranslation: "教师帮助学生准确使用新语言。",
        roleOptions: ["强调作用", "表示让步", "描述趋势", "引出结果"],
        roleExplanation: "在例句中强调教师对准确写作训练的重要性。",
        roleAnswer: "importance",
      },
    ],
    application: {
      context: "你想表达：AI 工具很方便，但学生仍需要老师指导，才能把新词准确用进写作。",
      prompt: "请用英文写 1 句，表达这个让步观点。",
      minChunks: 1,
      minWords: 10,
      sample: "Despite the fact that AI tools are convenient, teachers play a crucial role in writing practice.",
    },
  },
];
