export const BUILD_TASK = {
  id: "unit-3-listen-build-meaning",
  name: "听音拼写",
  grade: "高二",
  duration: "约 8 分钟",
};

export const BUILD_WORDS = [
  {
    id: "misleading",
    word: "misleading",
    phonetic: "/ˌmɪsˈliːdɪŋ/",
    partOfSpeech: "adj.",
    responseMode: "build",
    parts: ["mis", "lead", "ing"],
    tiles: ["mis", "read", "lead", "ness", "ing", "un"],
    morphology: [
      { part: "mis-", meaning: "错误地，不正确地" },
      { part: "lead", meaning: "引导" },
      { part: "-ing", meaning: "构成描述性质的形式" },
    ],
    meaning: "误导性的；使人产生错误想法的",
    meaningOptions: ["误导性的；使人产生错误想法的", "非常有帮助的", "可以重复使用的", "令人赞同的"],
  },
  {
    id: "unhelpful",
    word: "unhelpful",
    phonetic: "/ʌnˈhelpfl/",
    partOfSpeech: "adj.",
    responseMode: "build",
    parts: ["un", "help", "ful"],
    tiles: ["ful", "help", "less", "un", "hope", "re"],
    morphology: [
      { part: "un-", meaning: "不，非" },
      { part: "help", meaning: "帮助" },
      { part: "-ful", meaning: "充满...的，有...性质的" },
    ],
    meaning: "没有帮助的；无益的",
    meaningOptions: ["没有帮助的；无益的", "充满希望的", "非常谨慎的", "出乎意料的"],
  },
  {
    id: "careless",
    word: "careless",
    phonetic: "/ˈkeələs/",
    partOfSpeech: "adj.",
    responseMode: "build",
    parts: ["care", "less"],
    tiles: ["ful", "clear", "less", "care", "ness"],
    morphology: [
      { part: "care", meaning: "小心；关注" },
      { part: "-less", meaning: "没有，缺少" },
    ],
    meaning: "粗心的；不仔细的",
    meaningOptions: ["粗心的；不仔细的", "关心他人的", "清楚明白的", "害怕变化的"],
  },
  {
    id: "disagreement",
    word: "disagreement",
    phonetic: "/ˌdɪsəˈɡriːmənt/",
    partOfSpeech: "n.",
    responseMode: "build",
    parts: ["dis", "agree", "ment"],
    tiles: ["dis", "agree", "able", "ment", "appear", "un"],
    morphology: [
      { part: "dis-", meaning: "不，相反" },
      { part: "agree", meaning: "同意" },
      { part: "-ment", meaning: "表示状态或结果的名词后缀" },
    ],
    meaning: "分歧；意见不一致",
    meaningOptions: ["分歧；意见不一致", "达成一致", "一次重要发现", "明确的安排"],
  },
  {
    id: "preview",
    word: "preview",
    phonetic: "/ˈpriːvjuː/",
    partOfSpeech: "v./n.",
    responseMode: "build",
    parts: ["pre", "view"],
    tiles: ["pre", "view", "re", "visit", "ful"],
    morphology: [
      { part: "pre-", meaning: "在...之前" },
      { part: "view", meaning: "观看；查看" },
    ],
    meaning: "预览；预先观看",
    meaningOptions: ["预览；预先观看", "回顾并总结", "公开表演", "仔细调查"],
  },
  {
    id: "renewable",
    word: "renewable",
    phonetic: "/rɪˈnjuːəbl/",
    partOfSpeech: "adj.",
    responseMode: "build",
    parts: ["re", "new", "able"],
    tiles: ["new", "able", "re", "less", "mis", "ment"],
    morphology: [
      { part: "re-", meaning: "再次，重复" },
      { part: "new", meaning: "新的；更新" },
      { part: "-able", meaning: "可以...的" },
    ],
    meaning: "可再生的；可更新的",
    meaningOptions: ["可再生的；可更新的", "无法理解的", "容易误导的", "只使用一次的"],
  },
  {
    id: "good",
    word: "good",
    phonetic: "/ɡʊd/",
    partOfSpeech: "adj.",
    responseMode: "spell",
    meaning: "好的；优秀的",
    meaningOptions: ["好的；优秀的", "狭窄的", "吵闹的", "古老的"],
    spellingTip: "这个短词不按词缀拆解，注意中间有两个 o。",
  },
  {
    id: "busy",
    word: "busy",
    phonetic: "/ˈbɪzi/",
    partOfSpeech: "adj.",
    responseMode: "spell",
    meaning: "忙碌的；繁忙的",
    meaningOptions: ["忙碌的；繁忙的", "空闲的；无事可做的", "安静的；无声的", "健康的；强壮的"],
    spellingTip: "这个词的发音不能直接对应每一个字母，需整体记忆拼写。",
  },
  {
    id: "enough",
    word: "enough",
    phonetic: "/ɪˈnʌf/",
    partOfSpeech: "det./pron./adv.",
    responseMode: "spell",
    meaning: "足够的；充分的",
    meaningOptions: ["足够的；充分的", "昂贵的；奢侈的", "附近的；接近的", "不正确的；错误的"],
    spellingTip: "注意结尾 -ough 在这个词中读 /ʌf/。",
  },
  {
    id: "world",
    word: "world",
    phonetic: "/wɜːld/",
    partOfSpeech: "n.",
    responseMode: "spell",
    meaning: "世界；地球",
    meaningOptions: ["世界；地球", "森林；树林", "语言；文字", "工作；职业"],
    spellingTip: "这是整体拼写练习词，注意字母顺序。",
  },
];
